# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Testing

on: push

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - run: mvn clean test-compile
    - run: cd domain && mvn test
      
    - uses: barecheck/code-coverage-action@v0.1-beta.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: "./coverage/lcov.info"
        send-summary-comment: true
